env:
  browser: true
  es2021: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - only-warn
extends:
  - 'plugin:@typescript-eslint/recommended'
rules:
  semi: [ 1, always ]
  no-multiple-empty-lines: [ 1, { max: 2, maxEOF: 0 } ]
  prefer-const: 1
  arrow-body-style: [ 1, as-needed ]
  arrow-parens: [1, always]
  indent: [1, tab, { SwitchCase: 1 }]
  comma-dangle: [1, always-multiline]
  quote-props: [1, as-needed]
  object-curly-spacing: [1, always]
  object-curly-newline: [1, { multiline: true, consistent: true }]
  no-trailing-spaces: 1
  no-console: [1, { allow: [warn, error] }]
  quotes: [1, single]
  jsx-quotes: 1
  key-spacing: [ 1, { align: value } ]

  '@typescript-eslint/key-spacing': [ 1, { align: value } ]
  '@typescript-eslint/no-unused-vars': 1
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/no-non-null-assertion': 0
  '@typescript-eslint/ban-ts-comment': 0
  '@typescript-eslint/ban-types': 1

